service: rtkq-streaming-http-api

frameworkVersion: '2'

projectDir: ../

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.shared.deploymentBucket}
  deploymentPrefix: ${self:custom.basename}
  lambdaHashingVersion: 20201221
  memorySize: 256
  environment:
    SERVICE_NAME: ${self:service}
    BASE_NAME: ${self:custom.basename}
    MAIN_TABLE_NAME: ${self:custom.shared.resources.mainTableName}
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - ${self:custom.shared.resources.mainTableArn}
        - ${self:custom.shared.resources.mainTableIndexArns}

custom:
  basename: ${self:service}-${self:provider.stage}
  shared: ${file(../serverless.common.yml):shared}

functions:
  orders:
    handler: api-handlers/orders.handler
    events:
      - http:
          method: GET
          path: orders
          cors: true
          authorizer:
            name: storeAuthorizer
      - http:
          method: POST
          path: orders
          cors: true
          authorizer:
            name: storeAuthorizer
          request:
            schema:
              application/json: ${file(schema/createOrder.json)}

  clients:
    handler: api-handlers/clients.handler
    events:
      - http:
          method: POST
          path: clients
          cors: true
          # authorizer:
          #   name: storeAuthorizer
          # request:
          #   schema:
          #     application/json: ${file(schema/createOrder.json)}

  createFakeOrders:
    handler: cron-handlers/createFakeOrders.handler
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: false

  storeAuthorizer:
    handler: authorizers/storeAuthorizer.handler
