service: rardash-infrastructure

frameworkVersion: '2'

projectDir: ../

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.shared.deploymentBucket}
  deploymentPrefix: ${self:custom.basename}

custom:
  basename: ${self:service}-${self:provider.stage}
  shared: ${file(../serverless.common.yml):shared}

resources:
  Resources:
    # This can be useful for providing a default response in the case of a bad request
    # GatewayResponseDefault4XX:
    #   Type: 'AWS::ApiGateway::GatewayResponse'
    #   Properties:
    #     ResponseParameters:
    #       gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
    #       gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
    #     ResponseType: DEFAULT_4XX
    #     RestApiId:
    #       Ref: 'ApiGatewayRestApi'

    RARDashMain:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
      Properties:
        TableName: RARDashMain-${self:provider.stage}
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    RARDashConnections:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
      Properties:
        TableName: RARDashConnections-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            # pk = "CONNECTION"
            AttributeType: S
          - AttributeName: sk
            # sk is composite
            #   WEB_SOCKET_CONNECTION_ID#fakeId1234567890
            #   CLIENT_ID#54321
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE

  Outputs:
    RARDashMainName:
      Value: !Ref RARDashMain
      Export:
        Name: RARDashMainName
    RARDashMainArn:
      Value: !GetAtt RARDashMain.Arn
      Export:
        Name: RARDashMainArn
    RARDashMainStreamArn:
      Value: !GetAtt RARDashMain.StreamArn
      Export:
        Name: RARDashMainStreamArn
    RARDashMainIndexArns:
      Value: !Join ['/', [!GetAtt RARDashMain.Arn, 'index', '*']]
      Export:
        Name: RARDashMainIndexArns
    RARDashConnectionsName:
      Value: !Ref RARDashConnections
      Export:
        Name: RARDashConnectionsName
    RARDashConnectionsArn:
      Value: !GetAtt RARDashConnections.Arn
      Export:
        Name: RARDashConnectionsArn
